<a href="https://colab.research.google.com/github/Bhagath2005/B26_PFDS_1807/blob/main/LAB3_B26_1807.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print("2D + 1D Broadcasting:\n", A + B)
print("Shapes -> A:", A.shape, "B:", B.shape)

try:
    C = np.array([10, 20])  # shape (2,)
    print(A + C)            # Will raise error
except ValueError as e:
    print("\nInvalid Broadcasting Error:\n", e)

X = np.ones((2, 3, 4))
print("\n3D + Scalar Broadcasting:\n", X + 5)
print("Shapes -> X:", X.shape)

D = np.array([1, 2, 3])
print("\nOriginal D shape:", D.shape)
D_expanded = D[:, np.newaxis]   # shape (3,1)
print("Expanded D shape:", D_expanded.shape)

E = np.array([[10, 20, 30]])
print("\nBroadcasting Example (newaxis):\n", D_expanded + E)
print("Shapes -> D_expanded:", D_expanded.shape, "E:", E.shape)


2D + 1D Broadcasting:
 [[11 22 33]
 [14 25 36]]
Shapes -> A: (2, 3) B: (3,)

Invalid Broadcasting Error:
 operands could not be broadcast together with shapes (2,3) (2,) 

3D + Scalar Broadcasting:
 [[[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]

 [[6. 6. 6. 6.]
  [6. 6. 6. 6.]
  [6. 6. 6. 6.]]]
Shapes -> X: (2, 3, 4)

Original D shape: (3,)
Expanded D shape: (3, 1)

Broadcasting Example (newaxis):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Shapes -> D_expanded: (3, 1) E: (1, 3)


In [2]:
import numpy as np

arr = np.array([[4, -5, 16],
                [9, 25, -36]])
print("Original Array:\n", arr)

squared = arr ** 2
print("\nSquared Elements:\n", squared)

sqrted = np.sqrt(np.abs(arr))
print("\nSquare Root of Absolute Values:\n", sqrted)

non_negative = np.where(arr < 0, 0, arr)
print("\nNegative Replaced with Zero:\n", non_negative)

count_gt_10 = np.sum(non_negative > 10)
print("\nCount of Elements > 10:", count_gt_10)

mask = arr > 10
print("\nCondition Mask (arr > 10):\n", mask)

print("\nSummary:")
print(f"Original Shape: {arr.shape}")
print(f"Squared Shape: {squared.shape}")
print(f"Square Root Shape: {sqrted.shape}")
print(f"Mask Shape: {mask.shape}")


Original Array:
 [[  4  -5  16]
 [  9  25 -36]]

Squared Elements:
 [[  16   25  256]
 [  81  625 1296]]

Square Root of Absolute Values:
 [[2.         2.23606798 4.        ]
 [3.         5.         6.        ]]

Negative Replaced with Zero:
 [[ 4  0 16]
 [ 9 25  0]]

Count of Elements > 10: 2

Condition Mask (arr > 10):
 [[False False  True]
 [False  True False]]

Summary:
Original Shape: (2, 3)
Squared Shape: (2, 3)
Square Root Shape: (2, 3)
Mask Shape: (2, 3)
